services:

  subscription-api:
    container_name: subscription-api
    build:
      context: .
      dockerfile: Subscription.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - subscription-sqlserver
      - subscription-rabbitmq
      - subscription-seq
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=subscription-sqlserver,1433;Initial Catalog=master;User ID=sa;Password=Coti@2026;Encrypt=False
      - RabbitMQSettings__Host=subscription-rabbitmq
      - Seq__Url=http://subscription-seq:80
    networks:
      - subscription-network

  subscription-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: subscription-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Coti@2026
    ports:
      - "1434:1433"
    networks:
      - subscription-network
    volumes:
      - sqlserver-data:/var/opt/mssql

  subscription-rabbitmq:
    image: rabbitmq:3-management
    container_name: subscription-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672" 
      - "15672:15672"
    networks:
      - subscription-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  subscription-seq:
    image: datalust/seq:latest
    container_name: subscription-seq
    ports:
       - "5341:80"
    environment:
       - ACCEPT_EULA=Y
       - SEQ_FIRSTRUN_ADMINPASSWORD=Coti@2026
    networks:
       - subscription-network
    volumes:
       - seq_data:/data

networks:
  subscription-network:
    external: true
    name: shared-network

volumes:
  sqlserver-data:
  rabbitmq-data:
  seq_data: